apiVersion: v1
kind: Service
metadata:
  namespace: webserver
  name: webserver
spec:
  type: ClusterIP
  selector:
    app: webserver
  ports:
    - name: webserver-port
      port: 80
      targetPort: 80
