apiVersion: v1
kind: Service
metadata:
  namespace: postgres
  name: postgres-server
spec:
  type: ClusterIP
  selector:
    app: postgres-server
  ports:
    - name: postgres-port
      port: 5432
      targetPort: 5432
