apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: postgres
  name: postgres-server
spec:
  selector:
    matchLabels:
      app: postgres-server
  serviceName: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-server
    spec:
      containers:
        - name: postgres-database
          image: postgres:14.7-bullseye
          env:
            - name: POSTGRES_USER
              value: shaysrebellion
            - name: POSTGRES_PASSWORD
              value: postgresdb
            - name: POSTGRES_DB
              value: image_metadata
          ports:
            - name: postgres-port
              containerPort: 5432
          resources:
            requests:
              cpu: 500m
              memory: 500Mi
            limits:
              cpu: 1
              memory: 1Gi
          volumeMounts:
            - name: postgres-config
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: postgres-config
          configMap:
            name: postgres-config
