apiVersion: v1
kind: Service
metadata:
  namespace: redis-cluster
  name: redis-cluster
spec:
  type: ClusterIP
  ports:
    - name: client
      port: 6379
      targetPort: 6379
    - name: cluster
      port: 16379
      targetPort: 16379
  selector:
    app: redis-cluster
