apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: redis-cluster
  name: redis-cluster
spec:
  serviceName: redis-cluster
  replicas: 6
  selector:
    matchLabels:
      app: redis-cluster
  template:
    metadata:
      labels:
        app: redis-cluster
    spec:
      containers:
        - name: redis
          image: redis:bullseye
          ports:
            - name: client
              containerPort: 6379
            - name: cluster
              containerPort: 16379
          resources:
            requests:
              cpu: 250m
              memory: 250Mi
            limits:
              cpu: 500m
              memory: 500Mi
          volumeMounts:
            - name: conf
              mountPath: /conf
          command: ["redis-server", "/conf/redis.conf"]
      volumes:
        - name: conf
          configMap: 
            name: redis-cluster-config
